import type { Metadata } from "next";
import "./globals.css";
import ClientComponent from "./ClientComponent";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Gestion Employés",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster richColors position="bottom-right" />
        {/* <ClientComponent /> */}
        {children}
      </body>
    </html>
  );
}
